# Generated by Django 4.2.3 on 2023-08-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracker', '0003_alter_location_country_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
    ]
